### PR TITLE
Fixes/updates for compilation under gcc 15.1.0 -Wall -Wextra -Werror 

### LINKED ISSUE #94: Clean up warnings

### PR DESCRIPTION
**Pull request by rountree**
Fixes and updates to compile under gcc 15.1.0 with the flags `-Wall`, `-Wextra`, and `-Werror`.

Commits are based on the class of errors/warnings rather than files.

```
commit 47cb39:  Fixes three errors caused by stricter gcc defaults.
commit c6f85d:  Fixes one [-Wdiscarded-qualifiers] and one [-Wstringop-truncation].
commit a7260c:  Fixes fallthrough and initialization warnings.
commit acc263:  Fixes -Wsign-compare warnings.
commit 5182e8:  Fixes -Wformat warnings.
commit 32d0c6:  Suppresses -Wunused-parameter warnings by casting to void.
```
Fixes #94

### CODE REVIEW

**Comment by mplegendre** [comment]
This looks like it needs a rebase. Existing commits from both Nick and I are in here with changed hashes.
How does this relate to your other warning cleanup?

**Comment by rountree** [comment]
I closed out the other warning cleanup PR; this PR replaces it.  I'll get a rebase committed later this morning.

**Comment by rountree** [comment]
Just a single file needed cleanup.  Compiles without errors or warning with `-Wall -Wextra -Werror` using gcc-15.1.0 on Tuolumne.  All runTests passed.

File: src/biter/shmutil.h [hunk 1]
```diff
@@ -17,18 +17,20 @@ Place, Suite 330, Boston, MA 02111-1307 USA
...
 typedef struct {
    volatile unsigned long *lock;
-   volatile unsigned long *held_by;
+   volatile pid_t *held_by;
    int ref_count;
 } lock_t;
 
 typedef struct {
    volatile int cur_id;
-   unsigned long locks[2];
```
Comment (mplegendre) [inline src/biter/shmutil.h:31]: I'm nervous about changing the locks[] layout here. I don't remember why I wrote it this way, but I wouldn't have done something this odd without reason. Given that arrays and structs can have different packing (even if on x86_64 it shouldn't pack struct vs array different here), it might have had something to do with that. There's also some memory barriers around the code that uses these arrays, and there's always tough subtleties when those are involved.

That said, I can't re-determine why these should be arrays with just code inspection. And it's too bad I didn't comment why it's like this.

Given that this is a warning cleanup commit, let's not risk subtle semantic changes.

(And this applies to the two other array->struct conversions below as well)

File: src/client/client/realpath.c [hunk 2]
```diff
@@ -109,6 +109,7 @@ B. Use spindle versions of the IO accessing lower-level routines.
 The source file is glibc/stdlib/canonicalize.c at git commit 1894e219dc530d7074085e95ffe3c1e66cebc072
  */
 
+#pragma GCC diagnostic ignored "-Wsign-compare"
```
Comment (mplegendre) [inline src/client/client/realpath.c]: There are macros in src/utils/ccwarns.h for doing these

**Comment by mplegendre** [comment]
Also, it looks like you did a merge to resolve the conflicts. 
But it needs a rebase that adds only the warning commits. If you look at the commit list for the PR, there's several other commits that are already merged (but have different hashes in this PR).

File: src/client/client/realpath.c (hunk 2 above)
Comment (rountree) [reply src/client/client/realpath.c]: Those are handy.  I've narrowed the range of the disabled warning to a single `while` loop.  Putting the macro around the `while` test seems safe, but I'm not familiar with the rules of putting `#praga` within statements or across loop boundaries.

File: src/biter/shmutil.h (hunk 1 above)
Comment (rountree) [reply src/biter/shmutil.h:31]: Fixed.  Getting the `#include`s to work required updating a couple of `Makefile.am`s.

**Comment by rountree** [comment]
I just noticed that `-Wall -Wextra -Werror` is causing failures in the configure process.  These don't affect the results of `runTests`, but we might want to get those cleaned up.
